# Generated by Django 3.2.25 on 2025-03-24 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeworks/', verbose_name='作业图片')),
                ('correction_status', models.CharField(choices=[('PENDING', '待批改'), ('COMPLETED', '已批改')], default='PENDING', max_length=10, verbose_name='批改状态')),
                ('correction_result', models.TextField(blank=True, null=True, verbose_name='批改结果')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='分数')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='反馈')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('TEXT', '文字题目'), ('IMAGE', '图片题目')], default='TEXT', max_length=5, verbose_name='题目类型')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='文字内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/', verbose_name='题目图片')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='解答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
    ]
