# Generated by Django 3.2.25 on 2025-03-27 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homeworks/', verbose_name='作业图片')),
                ('correction_status', models.CharField(choices=[('PENDING', '待批改'), ('COMPLETED', '已批改')], default='PENDING', max_length=10, verbose_name='批改状态')),
                ('correction_result', models.TextField(blank=True, null=True, verbose_name='批改结果')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='分数')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='反馈')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('resource_type', models.CharField(choices=[('ARTICLE', '文章'), ('VIDEO', '视频'), ('BOOK', '书籍'), ('WEBSITE', '网站'), ('EXERCISE', '练习题')], max_length=10, verbose_name='资源类型')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习资源',
                'verbose_name_plural': '学习资源',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('TEXT', '文字题目'), ('IMAGE', '图片题目')], default='TEXT', max_length=5, verbose_name='题目类型')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='文字内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/', verbose_name='题目图片')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='解答')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='学校')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='年级')),
                ('subjects_of_interest', models.CharField(blank=True, max_length=200, null=True, verbose_name='感兴趣的科目')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='ResourceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='相关性分数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_recommendations', to='correction_system.problem', verbose_name='相关问题')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='correction_system.learningresource', verbose_name='学习资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源推荐',
                'verbose_name_plural': '资源推荐',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='上次复习时间')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_cards', to='correction_system.homework', verbose_name='相关作业')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_cards', to='correction_system.problem', verbose_name='相关问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_cards', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '知识卡片',
                'verbose_name_plural': '知识卡片',
                'ordering': ['-created_at'],
            },
        ),
    ]
