# Generated by Django 3.2.25 on 2025-03-27 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correction_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='平均评分'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='评价数量'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_resources', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.CreateModel(
            name='ResourceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='评分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='correction_system.learningresource', verbose_name='学习资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reviews', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源评价',
                'verbose_name_plural': '资源评价',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
